export const PRIORITY_TIMEZONES = [
  'UTC',
  // Asia
  'Asia/Tokyo',
  'Asia/Shanghai',
  'Asia/Hong_Kong',
  'Asia/Singapore',
  'Asia/Seoul',
  'Asia/Kolkata',
  'Asia/Dubai',
  'Asia/Bangkok',
  'Asia/Jakarta',
  'Asia/Taipei',
  'Asia/Manila',
  'Asia/Kuala_Lumpur',
  'Asia/Ho_Chi_Minh',
  'Asia/Riyadh',
  'Asia/Tehran',
  'Asia/Jerusalem',
  'Asia/Karachi',
  'Asia/Dhaka',
  'Asia/Yangon',
  'Asia/Kathmandu',
  'Asia/Baghdad',
  'Asia/Tashkent',
  'Asia/Almaty',
  // Europe
  'Europe/London',
  'Europe/Paris',
  'Europe/Berlin',
  'Europe/Rome',
  'Europe/Madrid',
  'Europe/Moscow',
  'Europe/Istanbul',
  'Europe/Kyiv',
  'Europe/Stockholm',
  'Europe/Zurich',
  'Europe/Athens',
  'Europe/Amsterdam',
  'Europe/Brussels',
  'Europe/Vienna',
  'Europe/Warsaw',
  'Europe/Prague',
  'Europe/Budapest',
  'Europe/Copenhagen',
  'Europe/Dublin',
  'Europe/Helsinki',
  'Europe/Lisbon',
  'Europe/Oslo',
  'Europe/Bucharest',
  // North America
  'America/New_York',
  'America/Chicago',
  'America/Los_Angeles',
  'America/Denver',
  'America/Phoenix',
  'America/Toronto',
  'America/Vancouver',
  'America/Mexico_City',
  'America/Montreal',
  'America/Monterrey',
  'America/Edmonton',
  'America/Winnipeg',
  'America/Havana',
  'America/Santo_Domingo',
  'America/Puerto_Rico',
  // South America
  'America/Sao_Paulo',
  'America/Argentina/Buenos_Aires',
  'America/Santiago',
  'America/Bogota',
  'America/Lima',
  'America/Caracas',
  'America/Montevideo',
  // Oceania
  'Australia/Sydney',
  'Australia/Melbourne',
  'Australia/Brisbane',
  'Australia/Perth',
  'Pacific/Auckland',
  'Australia/Adelaide',
  'Pacific/Fiji',
  // Africa
  'Africa/Cairo',
  'Africa/Johannesburg',
  'Africa/Lagos',
  'Africa/Nairobi',
  'Africa/Casablanca',
  'Africa/Accra',
  'Africa/Algiers',
  'Africa/Tunis',
  'Africa/Addis_Ababa',
  // Pacific/Atlantic
  'Pacific/Honolulu',
  'Atlantic/Reykjavik',
] as const;
