export const slackActionIds = {
  callScheduleEnabled: 'exe.call_schedule.enabled',
  callScheduleSkippedDates: 'exe.call_schedule.skipped_dates',
  callScheduleTime: 'exe.call_schedule.time',
  cancelTask: 'exe.cancel_task',
  channelOwnerEditorAssignees: 'exe.channel_owner_editor.assignees',
  channelOwnerEditorChannel: 'exe.channel_owner_editor.channel',
  channelSettingsAssignees: 'exe.channel_settings.assignees',
  channelWatchSettingsChannels: 'exe.channel_watch_settings.channels',
  completeTask: 'exe.complete_task',
  editTask: 'exe.edit_task',
  gbrainTokenCreate: 'exe.gbrain_token_create',
  gbrainTokenRevoke: 'exe.gbrain_token_revoke',
  manageAdminsChannelOwnerEditors: 'exe.manage_admins.channel_owner_editors',
  manageAdminsUsers: 'exe.manage_admins.users',
  openBilling: 'exe.open_billing',
  openCallScheduleSettings: 'exe.open_call_schedule_settings',
  openChannelOwnerEditor: 'exe.open_channel_owner_editor',
  openChannelSettings: 'exe.open_channel_settings',
  openChannelWatchSettings: 'exe.open_channel_watch_settings',
  openExeApp: 'exe.open_app',
  openGbrainConnect: 'exe.open_gbrain_connect',
  openManageAdmins: 'exe.open_manage_admins',
  openScheduledCallRunReschedule: 'exe.open_scheduled_call_run_reschedule',
  openSettings: 'exe.open_settings',
  refreshHome: 'exe.refresh_home',
  reopenTask: 'exe.reopen_task',
  rescheduleScheduledCallRun: 'exe.reschedule_scheduled_call_run',
  resolveChannelBlock: 'exe.resolve_channel_block',
  scheduledCallRunRescheduleDate: 'exe.scheduled_call_run.reschedule_date',
  scheduledCallRunRescheduleTime: 'exe.scheduled_call_run.reschedule_time',
  skipScheduledCallRun: 'exe.skip_scheduled_call_run',
  startTaskChangeCall: 'exe.start_task_change_call',
  taskEditAssignees: 'exe.task_edit.assignees',
  taskEditDueDate: 'exe.task_edit.due_date',
  taskEditDueTime: 'exe.task_edit.due_time',
  taskEditRequesters: 'exe.task_edit.requesters',
  taskEditTitle: 'exe.task_edit.title',
  taskOverflow: 'exe.task_overflow',
  workspaceSettingsLanguage: 'exe.workspace_settings.language',
  workspaceSettingsTimezone: 'exe.workspace_settings.timezone',
} as const;

export const slackBlockIds = {
  admin: 'exe.admin',
  callScheduleEnabled: 'exe.call_schedule.enabled',
  callScheduleSkippedDates: 'exe.call_schedule.skipped_dates',
  callScheduleTime: 'exe.call_schedule.time',
  channel: 'exe.channel',
  channelOwnerEditorAssignees: 'exe.channel_owner_editor.assignees',
  channelOwnerEditorChannel: 'exe.channel_owner_editor.channel',
  channelSettingsAssignees: 'exe.channel_settings.assignees',
  channelWatch: 'exe.channel_watch',
  channelWatchSettings: 'exe.channel_watch_settings',
  channelWatchSettingsChannels: 'exe.channel_watch_settings.channels',
  followUpTasks: 'exe.follow_up_tasks',
  manageAdminsChannelOwnerEditors: 'exe.manage_admins.channel_owner_editors',
  manageAdminsUsers: 'exe.manage_admins.users',
  nextCall: 'exe.next_call',
  openApp: 'exe.open_app',
  overdueTask: 'exe.overdue_task',
  scheduledCallRun: 'exe.scheduled_call_run',
  scheduledCallRunReschedule: 'exe.scheduled_call_run.reschedule',
  scheduledCallRunRescheduleDate: 'exe.scheduled_call_run.reschedule_date',
  scheduledCallRunRescheduleTime: 'exe.scheduled_call_run.reschedule_time',
  taskEditAssignees: 'exe.task_edit.assignees',
  taskEditDueDate: 'exe.task_edit.due_date',
  taskEditDueTime: 'exe.task_edit.due_time',
  taskEditRequesters: 'exe.task_edit.requesters',
  taskEditTitle: 'exe.task_edit.title',
  workspaceSettingsLanguage: 'exe.workspace_settings.language',
  workspaceSettingsTimezone: 'exe.workspace_settings.timezone',
  workTasks: 'exe.work_tasks',
} as const;

export const slackViewIds = {
  callScheduleSettings: 'exe.call_schedule_settings',
  channelOwnerEditor: 'exe.channel_owner_editor',
  channelSettings: 'exe.channel_settings',
  channelWatchSettings: 'exe.channel_watch_settings',
  gbrainConnect: 'exe.gbrain_connect',
  manageAdmins: 'exe.manage_admins',
  scheduledCallRunReschedule: 'exe.scheduled_call_run_reschedule',
  taskEdit: 'exe.task_edit',
  workspaceSettings: 'exe.workspace_settings',
} as const;
