import { createReactPackageConfig } from '../eslint.shared.mjs';

export default createReactPackageConfig({
  allowDefaultExport: true,
  allowTryStatements: true,
  configUrl: import.meta.url,
  extraGlobals: {
    AnalyserNode: 'readonly',
    AudioContext: 'readonly',
    Blob: 'readonly',
    Event: 'readonly',
    FileReader: 'readonly',
    HTMLButtonElement: 'readonly',
    HTMLInputElement: 'readonly',
    HTMLSelectElement: 'readonly',
    HTMLTextAreaElement: 'readonly',
    MediaRecorder: 'readonly',
    MediaStream: 'readonly',
    SVGSVGElement: 'readonly',
    URL: 'readonly',
    Uint8Array: 'readonly',
    atob: 'readonly',
    btoa: 'readonly',
    cancelAnimationFrame: 'readonly',
    localStorage: 'readonly',
    process: 'readonly',
    requestAnimationFrame: 'readonly',
    window: 'readonly',
  },
});
